# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

[PARSER]
    Name        nextcloud
    Format      json
    #Time_Key    time
    #Time_Format %Y-%m-%d %H:%M:%S
