#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="nextcloud"

check_service_initialized init 20-php-fpm


cat <<EOF

*******************************************************************************************
*                                                                                         *
*                    END OF LIFE NOTICE OCTOBER 8, 2025                                   *
*                               tiredofit/nextcloud                                       *
*                                                                                         *
* This image is no longer maintained as of and will not receive updates.                  *
*                                                                                         *
* A successor image is available at:                                                      *
*                                                                                         *
* Repository | Documentation:                                                             *
*   - https://github.com/nfrastack/container-nextcloud                                    *
*                                                                                         *
* Image Registries:                                                                       *
*   - https://hub.docker.com/r/nfrastack/nextcloud                                        *
*   - https://github.com/nfrastack/container-nextcloud/pkgs/container/container-nextcloud *
*                                                                                         *
* Please visit https://nfrastack.com for more information.                                *
*                                                                                         *
*******************************************************************************************

EOF

sleep 15

transform_file_var \
                        ADMIN_PASS \
                        ADMIN_USER \
                        DB_HOST \
                        DB_NAME \
                        DB_PASS \
                        DB_PORT \
                        DB_USER \
                        MONITORING_APPLICATION_TOKEN
check_databases
bootstrap_webroot
configure_data_directories
configure_logging
if var_true "${CONTAINER_ENABLE_FIREWALL}" && var_true "${CONTAINER_ENABLE_FAIL2BAN}" ; then configure_fail2ban_nextcloud; fi
install_nextcloud
create_configuration
configure_application_settings
custom_files "${CONTAINER_CUSTOM_PATH}" "${NGINX_WEBROOT}" "${NGINX_USER}" "${NGINX_GROUP}"
custom_scripts

print_info "Nextcloud Version ${NEXTCLOUD_VERSION} ready to be accessed!"
liftoff
