services:

  nextcloud-app:
    image: docker.io/nfrastack/nextcloud:32
    container_name: nextcloud-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.example.com`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-rep.redirectregex.replacement=https://$$1/remote.php/dav/
      - traefik.http.middlewares.nextcloud-rep.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud-header.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud-header.headers.stsSeconds=15552000
      - traefik.http.routers.nextcloud-app.middlewares=nextcloud-rep,nextcloud-header
    volumes:
      - ./data/apps:/data/apps
      - ./data/data:/data/userdata
      - ./data/config:/www/nextcloud/config
      - ./data/templates:/data/templates
      - ./data/themes:/www/nextcloud/themes
      - ./logs:/logs
    environment:
      - CRON_PERIOD=5

      - ADMIN_USER=admin
      - ADMIN_PASS=pass
      - DOMAIN=example.com

      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASS=password
      - DB_HOST=nextcloud-db
    networks:
      - proxy
      - services
    restart: always

  nextcloud-db:
    image: docker.io/tiredofit/mariadb:10.11
    container_name: nextcloud-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASS=password
    networks:
      - services
    restart: always

  nextcloud-redis:
    image: docker.io/nfrastack/redis:8
    container_name: nextcloud-redis
    volumes:
      - ./redis:/data
    environment:
      - ENABLE_PERSISTENCE=TRUE
    networks:
      - services
    restart: always

  nextcloud-db-backup:
    image: docker.io/tiredofit/db-backup:latest
    container_name: nextcloud-db-backup
    links:
      - nextcloud-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - DB01_HOST=nextcloud-db
      - DB01_TYPE=mariadb
      - DB01_NAME=nextcloud
      - DB01_USER=nextcloud
      - DB01_PASS=password
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB01_CLEANUP_TIME=8640
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
